[package]
name = "midired"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.3.0", features = ["canvas", "debug"] }

# Deps from iced "game_of_life" example
# https://github.com/iced-rs/iced/blob/master/examples/game_of_life/Cargo.toml
#iced = { path = "../..", features = ["canvas", "tokio", "debug"] }
#tokio = { version = "1.0", features = ["sync"] }
#itertools = "0.9"
#rustc-hash = "1.1"

# https://github.com/RustAudio/vst-rs
# vst = "0.2.1"

# https://github.com/negamartin/midly
# midly = "0.5"

# See for sound output
# https://github.com/RustAudio/rodio
# and/or
# https://github.com/RustAudio/cpal