[package]
name = "emmate"
version = "0.2.0"
edition = "2021"
authors = ["Petr <petrglad@gmail.com>"]
description = "A MIDI editor."
homepage = "https://github.com/PetrGlad/emmate"

# See also https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = 'abort'

[profile.release]
debug = true

[dependencies]

ordered-float = "4.2.2"

eframe = { version = "0.28.1" }
egui_extras = { version = "0.28.1" }

# https://github.com/negamartin/midly
midly = { version = "0.5.3", features = ["alloc"] }

# https://github.com/RustAudio/wmidi
wmidi = "4.0.10"

# https://github.com/Fluhzar/WAV
# wav = "1.0.0"
# Could also be https://github.com/ruuda/hound

# https://github.com/RustAudio/rodio
# rodio = "0.17.1"
# rodio = { path = "/home/petr/work/etc/rodio" }
# rodio = { git = "https://github.com/PetrGlad/rodio.git", branch = "configurable-buffer-size" }

# https://docs.rs/alsa/latest/alsa/
# apt install libasound2-dev
# alsa = "0.8.1"

# see also https://github.com/RustAudio/cpal
# cpal = "0.15.2"

# https://docs.rs/midir/0.7.0/midir/struct.MidiInput.html
midir = "0.10.0"

log = "0.4.22"
stderrlog = "~0.4" # >=0.5 have breaking dependency changes.

toml = "0.8.19"
serde = "1.0.209"
rmp = "0.8.14"
rmp-serde = "1.3.0"
clap = { version = "4.5.16", features = ["cargo"] }
chrono = "0.4.38"
glob = "0.3.1"
regex = "1.10.6"
flate2 = "1.0.33"
sync_cow = "0.1.1"
strum_macros = "0.26.4"
clap_complete = "4.5.24"
indoc = "2"
dirs = "5"
num = "0.4.3"
# rhai = "1.19.0"

# These may be useful
# tokio = { version = "1.0", features = ["sync"] }
# itertools = "0.9"
# rustc-hash = "1.1"
# bytes = "1.4.0"
# enum_dispatch = "0.3.12"
# rand = "0.8.5"

[dev-dependencies]
proptest = "1.5.0"
