[package]
name = "emmate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = 'abort'

[dependencies]

ordered-float = "4.1.0"

eframe = { version = "0.23.0" }
egui_extras = { version = "0.23.0" }

# https://github.com/RustAudio/vst-rs
vst = "0.3.0"

# https://github.com/negamartin/midly
midly = { version = "0.5.3", features = ["alloc"] }

# https://github.com/RustAudio/wmidi
wmidi = "4.0.8"

# https://github.com/Fluhzar/WAV
wav = "1.0.0"
# Could also be https://github.com/ruuda/hound

# https://github.com/RustAudio/rodio
# rodio = "0.17.1"
# rodio = { path = "/home/petr/work/etc/rodio" }
rodio = { git = "https://github.com/PetrGlad/rodio.git", branch = "configurable-buffer-size" }

# https://docs.rs/alsa/latest/alsa/
alsa = "0.8.1"

# see also https://github.com/RustAudio/cpal
cpal = "0.15.2"

# https://docs.rs/midir/0.7.0/midir/struct.MidiInput.html
midir = "0.9.1"

log = "0.4.20"
stderrlog = "0.5.4"

toml = "0.8.6"
serde = "1.0.191"
rmp = "0.8.12"
rmp-serde = "1.1.2"
clap = "4.4.6"
chrono = "0.4.31"
glob = "0.3.1"
regex = "1.10.2"

# These may be useful
# tokio = { version = "1.0", features = ["sync"] }
# itertools = "0.9"
# rustc-hash = "1.1"
# bytes = "1.4.0"
# enum_dispatch = "0.3.12"
# rand = "0.8.5"

[dev-dependencies]
proptest = "1.3.1"